<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */
    $mode ?>">

        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */
            '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */
            $mode ?> <?= /* @noEscape */
            $mode ?>">
                <ol class="product-items <?= /* @noEscape */
                $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                    <?php /* @noEscape */
                    $iterator++
                    ?>
                    <li class="product-item">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                            <div class="product-item-info">
                                <div class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </div>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                    <span title="<?= $block->escapeHtml($_item->getName()) ?>"
                                          class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </span>
                                    </strong>

                                    <?= $block->getProductPriceHtml($_item, $type) ?>

                                    <?= $block->getProductDetailsHtml($_item) ?>

                                    <div class="product-item-inner">
                                        <div class="actions-primary">
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available">
                                                    <ul>
                                                        <li><?= $block->escapeHtml(__('In stock')) ?></li>
                                                    </ul>
                                                </div>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'slick'
        ], function ($) {
            jQuery(document).ready(function () {
                jQuery(".widget-product-grid").slick({
                    dots: true,
                    infinite: true,
                    speed: 300,
                    slidesToShow: 4,
                    slidesToScroll: 4,
                    responsive: [
                        {
                            breakpoint: 1280,
                            settings: {
                                slidesToShow: 4,
                                slidesToScroll: 4
                            }
                        },
                        {
                            breakpoint: 1279,
                            settings: {
                                slidesToShow: 3,
                                slidesToScroll: 3
                            }
                        },
                        {
                            breakpoint: 1023,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                            }
                        },
                        {
                            breakpoint: 767,
                            settings: {
                                slidesToShow: 1,
                                slidesToScroll: 1
                            }
                        }
                    ]
                });
            });
        });
    </script>
<?php endif; ?>
