<?php
/**
 * @category    Edu
 * @package     Edu/StoreFinderCompletion
 * @author      Maxim Dzyuba <maxim.d@tdo.kz>

 */

use Edu\StoreFinderCompletion\Block\StoreList;
use Edu\StoreFinderCompletion\Helper\Data as DataHelper;

/**
 * @var StoreList $block
 */
?>
<div class="storefinder-store-list" data-bind="scope: 'storeList'">
    <div class="storefinder-list-head">
        <h2 class="storefinder-list-title" data-bind="i18n: 'Our Stores'"></h2>
        <div class="storefinder-list-filters">
            <?= $block->getCountrySelect() ?>
        </div>
        <a href="<?= $block->escapeUrl($block->getRetailStoreUrl()) ?>"
           class="storefinder-retail-link"><?= $block->getRetailStoreText() ?></a>
    </div>
    <div class="storefinder-stores">
        <!-- ko foreach: {data: stores, as: 'item'} -->
        <!-- ko template: 'Edu_StoreFinderCompletion/stores/store' --><!-- /ko -->
        <!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "storeList": {
                        "component": "storefinderStoreList",
                        "config": {
                            "ajaxUrl": "<?= $block->escapeUrl($block->getUrl(DataHelper::URL_LOAD_STORELIST)) ?>"
                        }
                    }
                }
            }
        }
    }
</script>
