<?php
/**
 * @category    Scandiweb
 * @package     Scandiweb/StoreFinder
 * @author      Andris Bremanis <info@scandiweb.com>
 * @copyright   Copyright (c) 2018 Scandiweb, Inc (https://scandiweb.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

use Scandiweb\StoreFinder\Block\RsvpPopup;

/**
 * @param $block RsvpPopup
 */
?>
<div id="rsvpPopup" class="rsvp-modal" data-bind="scope: 'rsvpPopup'" style="display: none">
    <div class="input-wrapper step-1">
        <div class="content-wrapper">
            <h2 class="title" data-bind="text: getTitleText()"></h2>
        </div>
        <div class="error-wrapper"></div>
        <form class="form form-rsvp"
              method="post"
              data-bind="event: { submit: submit }"
              id="rsvp-form"
              action="<?= $block->getAjaxUrl() ?>">
            <div class="email-wrapper">
                <input type="text" class="email" name="email"
                       data-bind="attr: { title: $t('Email Address'), placeholder: $t('Enter Your Email') }"
                       data-validate="{ required: true, 'validate-email': true }"
                       autocomplete="email" />
            </div>
            <div class="store-select-wrapper">
                <!-- ko if: isStoreArray() -->
                <select name="selected-store" class="store-select chosen-active" data-bind="chosen: {}">
                    <!-- ko foreach: stores -->
                    <option data-bind="value: store_id, text: name"></option>
                    <!-- /ko -->
                </select>
                <!-- /ko -->
                <!-- ko ifnot: isStoreArray() -->
                <input type="hidden" name="selected-store" data-bind="value: getOnlyStoreId()" />
                <!-- /ko -->
            </div>
        </form>
    </div>
    <div class="message-wrapper step-2">
        <div class="title-wrapper">
            <h2 class="title" data-bind="text: getThankYouTitleText()"></h2>
        </div>
        <div class="data-wrapper">
            <div class="title-wrapper">
                <span class="title"><?= $block->escapeHtml(__('Time and Location details')) ?></span>
            </div>
            <div class="details-wrapper">
                <div class="date-wrapper">
                    <span class="month" data-bind="text: getMonth()"></span>
                    <span class="date" data-bind="text: getDay()"></span>
                </div>
                <div class="time-wrapper">
                    <span class="time" data-bind="text: getTimeString()"></span>
                </div>
                <div class="store-wrapper">
                    <span class="store-name" data-bind="text: store().name"></span>
                    <div class="address" data-bind="html: store().address"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#rsvpPopup": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "rsvpPopup": {
                        "component": "storefinderRsvpPopup",
                        "config": {
                            "popupSelector": "#rsvpPopup",
                            "formSelector": "#rsvp-form",
                            "selectStoreSelector": "[name=selected-store]",
                            "emailSelector": "[name=email]",
                            "errorMessageWrapperSelector": ".error-wrapper"
                        }
                    }
                }
            }
        }
    }
</script>
