<?php
/**
 * @category    Edu
 * @package     Edu/StoreFinderCompletion
 * @author      Maxim Dzyuba <maxim.d@tdo.kz>

 */

use Edu\StoreFinderCompletion\Block\EventList;
use Edu\StoreFinderCompletion\Helper\Data as DataHelper;

/**
 * @var EventList $block
 */
?>
<div class="storefinder-event-list" data-bind="scope: 'eventList'">
    <?php if ($block->getHeadImageUrl() !== null) : ?>
    <div class="head-image">
        <img src="<?= $block->getHeadImageUrl() ?>" alt="<?= __('Event list page head image') ?>">
    </div>
    <?php endif ?>
    <div class="storefinder-list-head">
        <h2 class="storefinder-list-title" data-bind="i18n: 'Upcoming Events'"></h2>
        <div class="storefinder-list-filters">
            <?= $block->getCountrySelect() ?>
        </div>
    </div>
    <div class="storefinder-events">
        <!-- ko foreach: {data: events, as: 'item'} -->
        <!-- ko template: 'Edu_StoreFinderCompletion/events/event' --><!-- /ko -->
        <!-- /ko -->
        <div class="loading-mask" data-bind="css: { visible: loadingInProgress }">
            <img src="<?= $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= $block->escapeHtml(__('Loading mask')) ?>" />
        </div>
    </div>
    <div class="lazy-load-trigger" data-bind="event: { lazyload: lazyLoad }"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "eventList": {
                        "component": "storefinderEventList",
                        "config": {
                            "ajaxUrl": "<?= $block->escapeUrl($block->getUrl(DataHelper::URL_LOAD_EVENTLIST)) ?>",
                            "rsvpPopup": "rsvpPopup"
                        }
                    }
                }
            }
        }
    }
</script>
