<?php
/**
 * @category Edu
 * @package Edu\CmsSimpleBadge
 * @author Maxim Dzyuba <maxim.d@tdo.kz>
 */
// @codingStandardsIgnoreFile
use Magento\Catalog\Block\Product\AbstractProduct;
use Edu\CmsSimpleBadge\Block\Product\ProductList\Related;
use Magento\Framework\Exception\NoSuchEntityException;

/* @var $block AbstractProduct */

$type = $block->getType();
if ($type == 'related') {
    /** @var Related $block */
    if ($exist = $block->getItems()->getSize()) {
        $type = 'related';
        $class = $type;

        $image = 'related_products_list';
        $title = __('Related Products');
        $items = $block->getItems();
        $limit = 0;
        $shuffle = 0;
        $canItemsAddToCart = $block->canItemsAddToCart();

        $showAddTo = true;
        $showCart = false;
        $templateType = null;
        $description = false;
    }
} else {
    $exist = null;
}

if ($exist): ?>
    <div class="block <?= /* @escapeNotVerified */
        $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
        data-limit="<?= /* @escapeNotVerified */
        $limit ?>" data-shuffle="<?= /* @escapeNotVerified */
        $shuffle ?>">

        <div class="block-title title">
            <strong id="block-<?= /* @escapeNotVerified */
                $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */
                $title ?>
            </strong>
        </div>

        <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */
            $class ?>-heading">

            <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */
                $type ?>">
                <ol class="products list items product-items" id="<?= $type; ?>">
                    <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <li class="item product product-item" style="display: none;">
                            <div class="product-item-info">
                                <?= /* @escapeNotVerified */
                                '<!-- ' . $image . '-->' ?>
                                <?php
                                    $badgesList = $_item->getData('badges_list');
                                    try {
                                        echo $block->getBadge($badgesList);
                                    } catch (NoSuchEntityException $e) {
                                        print_r($e);
                                    }
                                ?>
                                <a href="<?= /* @escapeNotVerified */
                                $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>

                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           title="<?= $block->escapeHtml($_item->getName()) ?>"
                                           href="<?= /* @escapeNotVerified */
                                           $block->getProductUrl($_item) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                    <?= /* @escapeNotVerified */
                                    $block->getProductPrice($_item) ?>

                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available">
                                            <span><?= /* @escapeNotVerified */
                                                __('In stock') ?></span>
                                        </div>
                                    <?php else: ?>
                                        <div class="stock unavailable">
                                            <span><?= /* @escapeNotVerified */
                                                __('Out of stock') ?></span>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'slick'
        ], function ($) {
            jQuery(document).ready(function () {
                jQuery("#related").slick({
                    dots: true,
                    infinite: true,
                    speed: 300,
                    slidesToShow: 4,
                    slidesToScroll: 4,
                    responsive: [
                        {
                            breakpoint: 1280,
                            settings: {
                                slidesToShow: 3,
                                slidesToScroll: 3
                            }
                        },
                        {
                            breakpoint: 768,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                            }
                        },
                        {
                            breakpoint: 600,
                            settings: {
                                slidesToShow: 1,
                                slidesToScroll: 1
                            }
                        }
                    ]
                });
            });
        });
    </script>
<?php endif;?>
