<?php
/**
 * @category    Scandiweb
 * @package     Scandiweb/StoreFinder
 * @author      Andris Bremanis <info@scandiweb.com>
 * @copyright   Copyright (c) 2018 Scandiweb, Inc (https://scandiweb.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

use Scandiweb\StoreFinder\Block\ListPage;

/**
 * @var ListPage $block
 */
$eventListActive = $block->isEventList() ? 'active' : '';
$storeListActive = $block->isStoreList() ? 'active' : '';
?>
<div class="storefinder-list-page">
    <div class="list-page-menu">
        <div class="menu-store-button <?= $storeListActive ?>"
             data-action="storefinder-open-stores">
            <span class="label"><?= $block->escapeHtml(__('Stores')) ?></span>
        </div>
        <div class="menu-event-button <?= $eventListActive ?>"
             data-action="storefinder-open-events">
            <span class="label"><?= $block->escapeHtml(__('Events')) ?></span>
        </div>
    </div>
    <div class="store-list-wrapper <?= $storeListActive ?>"
         id="storefinder-store-list-wrapper">
        <?= $block->getChildHtml('storefinder.list.stores'); ?>
    </div>
    <div class="event-list-wrapper <?= $eventListActive ?>"
         id="storefinder-event-list-wrapper">
        <?= $block->getChildHtml('storefinder.list.events'); ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "storefinderListPage": {
                        "component": "storefinderListPage",
                        "config": {
                            "eventPageUrl": "<?= $block->getEventPageUrl() ?>",
                            "storePageUrl": "<?= $block->getStorePageUrl() ?>"
                        }
                    }
                }
            }
        }
    }
</script>
