<?php
/**
 * @category    Scandiweb
 * @package     Scandiweb/StoreFinder
 * @author      Andris Bremanis <info@scandiweb.com>
 * @copyright   Copyright (c) 2018 Scandiweb, Inc (https://scandiweb.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

use Scandiweb\StoreFinder\Block\StoreDetailsPage;
use Scandiweb\StoreFinder\Helper\Data as DataHelper;

/**
 * @var StoreDetailsPage $block
 */

$images = $block->getImageUrls();
?>
<div class="storefinder-store-details-page" data-bind="scope: 'storeEventList'">
    <div class="head">
        <div class="back">
            <a href="<?= $block->getReturnUrl() ?>">
                <span class="icon">&#8592;</span>
                <span class="label"><?= $block->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
        <?php if (!empty($images)) : ?>
        <div class="image-slider">
            <?php foreach ($images as $imageUrl) : ?>
            <div class="image">
                <img src="<?= $imageUrl ?>"
                     alt="<?= $block->escapeHtml(__('Image of store %1', $block->getTitle())) ?>">
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif ?>
        <div class="title-block">
            <h1 class="title-text"><?= $block->getTitle() ?></h1>
            <div class="description">
                <p class="description-text"><?= $block->getDescription() ?></p>
            </div>
            <div class="booking">
                <!-- TODO: Add in future task (task id: TBD) -->
            </div>
        </div>
    </div>
    <div class="details">
        <div class="address-block">
            <h2 class="address"><?= $block->getAddress() ?></h2>
            <div class="direction-url-row">
                <a href="<?= $block->getDirectionsUrl() ?>" target="_blank" class="direction-url">
                    <span class="direction-icon"></span>
                    <span class="direction-label"><?= $block->escapeHtml(__('Get Directions')) ?></span>
                </a>
            </div>
        </div>
        <div class="contact-block">
            <div class="store-contacts">
                <h3 class="title"><?= $block->escapeHtml(__('Store Contact')) ?></h3>
                <div class="phone-row">
                    <span class="phone-icon"></span>
                    <span class="phone-label"><?= $block->escapeHtml(__('Phone')) ?></span>
                    <span class="phone-value"><?= $block->getStorePhone() ?></span>
                </div>
                <div class="email-row">
                    <span class="email-icon"></span>
                    <span class="email-label"><?= $block->escapeHtml(__('Email')) ?></span>
                    <span class="email-value"><?= $block->getStoreEmail() ?></span>
                </div>
            </div>
            <div class="manager-contacts">
                <h3 class="title"><?= $block->escapeHtml(__('Store Manager')) ?>
                    <span class="name"><?= $block->getManagerName() ?></span>
                </h3>
                <div class="phone-row">
                    <span class="phone-icon"></span>
                    <span class="phone-label"><?= $block->escapeHtml(__('Phone')) ?></span>
                    <span class="phone-value"><?= $block->getManagerPhone() ?></span>
                </div>
                <div class="email-row">
                    <span class="email-icon"></span>
                    <span class="email-label"><?= $block->escapeHtml(__('Email')) ?></span>
                    <span class="email-value"><?= $block->getManagerEmail() ?></span>
                </div>
            </div>
        </div>
        <div class="store-hours-block">
            <h3 class="title"><?= $block->escapeHtml(__('Store Hours')) ?></h3>
            <div class="content"><?= $block->getStoreHours() ?></div>
        </div>
        <?php if ($block->isShowAdditionalInfo()) : ?>
        <div class="additional-info-block">
            <div class="content"><?= $block->getAdditionalInfo() ?></div>
        </div>
        <?php endif; ?>
    </div>
    <div class="storefinder-events active" data-bind="css: { 'hidden': emptyEventList() }">
        <h2 class="storefinder-events-title"><?= $block->escapeHtml(__('Upcoming Events')) ?></h2>
        <!-- ko foreach: {data: events, as: 'item'} -->
        <!-- ko template: 'Scandiweb_StoreFinder/events/event' --><!-- /ko -->
        <!-- /ko -->
    </div>
    <div class="underlay"></div>
</div>
<script type="text/javascript">
    require(['jquery', 'slickSlider', 'domReady!'], function ($) {
        $('.storefinder-store-details-page .image-slider').slick({
            arrows: false,
            dots: true
        });

        var repositionUnderlay = function () {
            var top = 120 + $(".storefinder-store-details-page .head .title-text").height();
            $(".storefinder-store-details-page .underlay").css("top", top);
        };

        $(window).resize(repositionUnderlay);
        repositionUnderlay();
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "storeEventList": {
                        "component": "storefinderStoreDetailEventList",
                        "config": {
                            "listSelector": ".storefinder-events",
                            "ajaxUrl": "<?= $block->escapeUrl($block->getUrl(DataHelper::URL_LOAD_EVENTLIST)) ?>",
                            "rsvpPopup": "rsvpPopup",
                            "storeId": "<?= $block->getStoreId() ?>"
                        }
                    }
                }
            }
        }
    }
</script>
