<?php
/**
 * @category    Edu
 * @package     Edu/StoreFinderCompletion
 * @author      Maxim Dzyuba <maxim.d@tdo.kz>

 */

use Edu\StoreFinderCompletion\Block\Gmap;

/**
 * @var Gmap $block
 */

$template = $block->getInfoWindowTemplate();
?>
<script type="text/javascript">
    window.googleMapsApiKey = "<?= $block->getGoogleApiKey() ?>";
    window.googleMapsMarkerIcon = "<?= $block->escapeUrl($block->getMapMarkerIcon()) ?>";
    <?php if ($template !== null) : ?>
    window.googleMapsInfoWindowTemplate = <?= json_encode($template) ?>;
    <?php else : ?>
    window.googleMapsInfoWindowTemplate = '<h4>%store_name%</h4>';
    <?php endif ?>
    window.googleMarkerClustererStyles = [{
        "url": "<?= $block->escapeUrl($block->getMarkerClustererIcon('m1.png')) ?>",
        "height": 53,
        "width": 53
    }, {
        "url": "<?= $block->escapeUrl($block->getMarkerClustererIcon('m2.png')) ?>",
        "height": 56,
        "width": 56
    }, {
        "url": "<?= $block->escapeUrl($block->getMarkerClustererIcon('m3.png')) ?>",
        "height": 66,
        "width": 66
    }, {
        "url": "<?= $block->escapeUrl($block->getMarkerClustererIcon('m4.png')) ?>",
        "height": 78,
        "width": 78
    }, {
        "url": "<?= $block->escapeUrl($block->getMarkerClustererIcon('m5.png')) ?>",
        "height": 90,
        "width": 90
    }];
</script>
